# use java 25 - might have to resort to java 17 or 21 for something that is more stable...
FROM eclipse-temurin:25-jdk

# set working directory
WORKDIR /app

# copy everything into the container
COPY . .

# build the springboot app
RUN ./mvnw clean package -DskipTests

# expose port (render provides PORT env var)
EXPOSE 8080

# run the app
CMD ["sh", "-c", "java", "-jar", "target/*jar"]